[[redirects]]
  from = "https://dripzels.spacedorito.xyz/*"
  to = "https://dripzels.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dripzels.spacedorito.com/*"
  to = "https://dripzels.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dripzels.netlify.app/*"
  to = "https://dripzels.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404